// ========================================
// Create Category
// ========================================

// Import Discord Type
import { Message } from "discord.js";
// Import Crew Interface
import Crew from "../../db/models/Crews/crews_attributes";
// Import Config
import { roles } from "../../config.json";

// Create Crew Category
export default async function createCategory(mgs: Message, crew: Crew) {
  // Create Category
  return await mgs.guild?.channels.create(crew.name, {
    type: "category",
    permissionOverwrites: [
      {
        id: roles.server_staffer,
        allow: [
          "VIEW_CHANNEL",
          "MANAGE_CHANNELS",
          "MANAGE_ROLES",
          "CREATE_INSTANT_INVITE",
          "SEND_MESSAGES",
          "EMBED_LINKS",
          "ATTACH_FILES",
          "ADD_REACTIONS",
          "USE_EXTERNAL_EMOJIS",
          "MANAGE_MESSAGES",
          "READ_MESSAGE_HISTORY",
          "SPEAK",
          "STREAM",
          "USE_VAD",
          "MUTE_MEMBERS",
          "MOVE_MEMBERS",
          "CONNECT",
          "DEAFEN_MEMBERS",
        ],
        deny: [
          "MENTION_EVERYONE",
          "MANAGE_WEBHOOKS",
          "SEND_TTS_MESSAGES",
          "PRIORITY_SPEAKER",
        ],
      },
      {
        id: roles.staff,
        allow: [
          "VIEW_CHANNEL",
          "CREATE_INSTANT_INVITE",
          "SEND_MESSAGES",
          "EMBED_LINKS",
          "ATTACH_FILES",
          "ADD_REACTIONS",
          "USE_EXTERNAL_EMOJIS",
          "MANAGE_MESSAGES",
          "READ_MESSAGE_HISTORY",
          "SPEAK",
          "STREAM",
          "USE_VAD",
          "MUTE_MEMBERS",
          "MOVE_MEMBERS",
          "CONNECT",
          "DEAFEN_MEMBERS",
        ],
        deny: [
          "MANAGE_CHANNELS",
          "MANAGE_ROLES",
          "MANAGE_WEBHOOKS",
          "MENTION_EVERYONE",
          "SEND_TTS_MESSAGES",
          "PRIORITY_SPEAKER",
        ],
      },
      {
        id: roles.passaporta,
        allow: [
          "VIEW_CHANNEL",
          "CREATE_INSTANT_INVITE",          
          "SPEAK",
          "STREAM",
          "USE_VAD",
          "MOVE_MEMBERS",
          "CONNECT",
        ],
        deny: [
          "SEND_MESSAGES",
          "EMBED_LINKS",
          "ATTACH_FILES",
          "ADD_REACTIONS",
          "USE_EXTERNAL_EMOJIS",
          "READ_MESSAGE_HISTORY",
          "MUTE_MEMBERS",
          "MANAGE_CHANNELS",
          "MANAGE_ROLES",
          "MANAGE_WEBHOOKS",
          "MENTION_EVERYONE",
          "MANAGE_MESSAGES",
          "SEND_TTS_MESSAGES",
          "PRIORITY_SPEAKER",
          "DEAFEN_MEMBERS",
        ],
      },
      {
        id: roles.schiavo,
        deny: [
          "VIEW_CHANNEL",
          "CREATE_INSTANT_INVITE",
          "SEND_MESSAGES",
          "EMBED_LINKS",
          "ATTACH_FILES",
          "ADD_REACTIONS",
          "USE_EXTERNAL_EMOJIS",
          "READ_MESSAGE_HISTORY",
          "SPEAK",
          "STREAM",
          "USE_VAD",
          "MUTE_MEMBERS",
          "MOVE_MEMBERS",
          "CONNECT",
          "MANAGE_CHANNELS",
          "MANAGE_ROLES",
          "MANAGE_WEBHOOKS",
          "MENTION_EVERYONE",
          "MANAGE_MESSAGES",
          "SEND_TTS_MESSAGES",
          "PRIORITY_SPEAKER",
          "DEAFEN_MEMBERS",
        ],
      },
      {
        id: roles.pirata_veterano,
        allow: ["CREATE_INSTANT_INVITE", "SPEAK", "STREAM", "VIEW_CHANNEL","USE_VAD","READ_MESSAGE_HISTORY",],
        deny: [
          "SEND_MESSAGES",
          "EMBED_LINKS",
          "ATTACH_FILES",
          "ADD_REACTIONS",
          "USE_EXTERNAL_EMOJIS",
          "MANAGE_CHANNELS",
          "MANAGE_ROLES",
          "MANAGE_WEBHOOKS",
          "MENTION_EVERYONE",
          "MANAGE_MESSAGES",
          "SEND_TTS_MESSAGES",
          "CONNECT",
          "PRIORITY_SPEAKER",
          "MUTE_MEMBERS",
          "DEAFEN_MEMBERS",
          "MOVE_MEMBERS",
        ],
      },
      {
        id: roles.tortuga,
        allow: ["CREATE_INSTANT_INVITE", "SPEAK", "STREAM", "VIEW_CHANNEL","USE_VAD","READ_MESSAGE_HISTORY"],
        deny: [          
          "SEND_MESSAGES",
          "EMBED_LINKS",
          "ATTACH_FILES",
          "ADD_REACTIONS",
          "USE_EXTERNAL_EMOJIS",
          "MANAGE_CHANNELS",
          "MANAGE_ROLES",
          "MANAGE_WEBHOOKS",
          "MENTION_EVERYONE",
          "MANAGE_MESSAGES",
          "SEND_TTS_MESSAGES",
          "CONNECT",
          "PRIORITY_SPEAKER",
          "MUTE_MEMBERS",
          "DEAFEN_MEMBERS",
          "MOVE_MEMBERS",
        ],
      },
      {
        id: roles.everyone,
        allow: ["SPEAK", "STREAM", "USE_VAD"],
        deny: [
          "CREATE_INSTANT_INVITE",
          "SEND_MESSAGES",
          "EMBED_LINKS",
          "ATTACH_FILES",
          "ADD_REACTIONS",
          "USE_EXTERNAL_EMOJIS",
          "READ_MESSAGE_HISTORY",
          "VIEW_CHANNEL",
          "MANAGE_CHANNELS",
          "MANAGE_ROLES",
          "MANAGE_WEBHOOKS",
          "MENTION_EVERYONE",
          "MANAGE_MESSAGES",
          "SEND_TTS_MESSAGES",
          "CONNECT",
          "PRIORITY_SPEAKER",
          "MUTE_MEMBERS",
          "DEAFEN_MEMBERS",
          "MOVE_MEMBERS",
        ],
      },
      {
        id: crew.crewId,
        allow: [
          "VIEW_CHANNEL",
          "CREATE_INSTANT_INVITE",
          "CONNECT",
          "SPEAK",
          "STREAM",
          "USE_VAD",
          "MOVE_MEMBERS",
          "SEND_MESSAGES",
          "EMBED_LINKS",
          "ATTACH_FILES",
          "ADD_REACTIONS",
          "USE_EXTERNAL_EMOJIS",
          "READ_MESSAGE_HISTORY",
        ],
        deny: [
          "MANAGE_CHANNELS",
          "MANAGE_ROLES",
          "PRIORITY_SPEAKER",
          "MUTE_MEMBERS",
          "DEAFEN_MEMBERS",
          "MANAGE_WEBHOOKS",
          "MENTION_EVERYONE",
        ],
      },
    ],
  });
}
